---
name: Code Style
on:
  - push
  - pull_request
jobs:
  prettier:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - name: run prettier check
        run: npm run ci-prettier

